#!/usr/bin/env bash
#### Sonar - A WiFi Keepalive daemon
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022
#### https://github.com/mainsail-crew/sonar
####
#### This File is distributed under GPLv3
####

# shellcheck disable=all

# Error handling
# set -x # Uncomment for debugging purposes
set -e

source /common.sh
install_cleanup_trap

echo_green "Installing sonar and enable sonar Service ..."
# install dependencies
# force apt update
apt update
check_install_pkgs ${SONAR_SONAR_DEPS}
# Move to $HOME dir
pushd /home/${BASE_USER} &> /dev/null || exit 1
    # clone Repo
    echo_green "Clone sonar repository ..."
    gitclone SONAR_SONAR_REPO sonar
    # install sonar
    pushd /home/${BASE_USER}/sonar &> /dev/null || exit 1
    echo_green "Running sonar installer ..."
    sudo -u "${BASE_USER}" make install
    popd &> /dev/null || exit 1
popd &> /dev/null || exit 1
