#!/bin/env bash
#### Sonar - A WiFi Keepalive daemon
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022
#### https://github.com/mainsail-crew/sonar
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces

# Exit on Errors
set -Ee

# Make sure script runs with root priviledges
if [ "$(id -u)" != "0" ]; then
    echo -e "\nSonar - A WiFi Keepalive daemon\n"
    echo -e "This Script is not intended to run as ${USER}!\n"
    echo -e "ERROR: Reporting to log and exiting."
    exit 1
fi

# Base Paths
BASE_SNR_PATH="$(dirname "$(readlink -f "${0}")")"
BASE_USER_HOME="$(dirname "${BASE_SNR_PATH}")"
export BASE_USER_HOME
SNR_LOG_PATH="/var/log/sonar.log"
export SNR_LOG_PATH

# General configuration is done by function setup_defaults
# See libs/core.sh L#100

## Import Librarys
# shellcheck source-path=SCRIPTDIR/libs/
source "${BASE_SNR_PATH}/libs/configparser.sh"
source "${BASE_SNR_PATH}/libs/core.sh"
source "${BASE_SNR_PATH}/libs/logging.sh"
source "${BASE_SNR_PATH}/libs/messages.sh"

#### MAIN
## Args given?
if [ "$#" -ne 0 ]; then
    ## Parse Args
    while getopts ":vhc:" arg; do
        case "${arg}" in
            v )
                echo -e "\nSonar Version: $(self_version)\n"
                exit 0
            ;;
            h )
                help_msg
                exit 0
            ;;
            c )
                export SONAR_CFG="${OPTARG}"
            ;;
            \?)
                wrong_args_msg
                exit 1
            ;;
        esac
    done
fi

init_log_entry
initial_check
while true; do
    keepalive
    sleep "${SONAR_CHECK_INTERVAL}"
done

exit 0
